adafruit/Adafruit_Blinka_Displayio

- setup.py
Fixes #22. The issue was that setup.py was configured to only work with files and not folders. Tested by copying to the Pi and running `pip3 install .`
> Fixed setup to work with folders

- displayio/display.py
- displayio/tilegrid.py
- terminalio.py
This fixes a divide by zero error when tilegrids are supplied 0,0 for the size (as spotted from a recent display text update) and also speeds up displayio significantly by fixing a bug that caused the display to accumulate dirty rectangles on each refresh.
> Divide by zero and speed up bug fixes

- displayio/display.py
This implements the fill_row() function. Solves #12.
I tested by using the edited [BitmapSaver library from PR #12 on that repo](https://github.com/adafruit/Adafruit_CircuitPython_BitmapSaver/pull/12) and this code:
```python
import board
from adafruit_bitmapsaver import save_pixels
import terminalio
from adafruit_display_text import label
import adafruit_ili9341
displayio.release_displays()
spi = board.SPI()
tft_cs = board.CE0
tft_dc = board.D25
display_bus = displayio.FourWire(
spi, command=tft_dc, chip_select=tft_cs, reset=board.D24
)
display = adafruit_ili9341.ILI9341(display_bus, width=320, height=240)
text = "Hello world"
text_area = label.Label(terminalio.FONT, text=text)
text_area.x = 10
text_area.y = 10
display.show(text_area)
print("Taking Screenshot...") …
```
> Implement fill_row

- displayio/tilegrid.py
Fixes #34. This has the additional benefit of not drawing unnecessary stuff and potentially speeding it up a bit.
> Avoid drawing offscreen stuff

- displayio/bitmap.py
- displayio/group.py
- displayio/i2cdisplay.py
- displayio/parallelbus.py
- displayio/tilegrid.py
Fixes #52. There was really only one area that I saw that actually benefited from removing duplicated code. I just changed private variable names or added NotImplemented errors for the rest. Either way, this shouldn't block folks anymore.
> Fix code duplication warnings

- displayio/tilegrid.py
I found that this basic TileGrid example was drawing an extra part of the spritesheet.
```python
from blinka_displayio_pygamedisplay import PyGameDisplay
import adafruit_imageload
display = PyGameDisplay(width=160 * 2, height=128 * 2)
main_group = displayio.Group(max_size=10)
display.show(main_group)
sprite_sheet, palette = adafruit_imageload.load("sprite_sheet_diff.bmp",
bitmap=displayio.Bitmap,
palette=displayio.Palette)
entities = displayio.TileGrid(sprite_sheet, pixel_shader=palette,
width=10,
height=8,
tile_width=16,
tile_height=16,
default_tile=17)
entity_group = displayio.Group(scale=2)
entity_group.append(entities)
main_group.append(entity_group)
palette.make_transparent(20)
entities[3, 3] = 0
while display.running:
pass
```
This is the bmp filed used: …
> tilegrid size fix

- displayio/display.py
For #56. Simple change from `list` to `bytes`. Recreated original issue and confirmed this fix works.
This is saved as **tft_test.py**
```python
import time
import board
import busio
from adafruit_featherwing import minitft_featherwing
i2c = board.I2C()
spi = busio.SPI(board.SCK1, board.MOSI1, board.MISO1)
fw = minitft_featherwing.MiniTFTFeatherWing(i2c=i2c, spi=spi, cs=board.GP15, dc=board.GP14)
bmp = displayio.Bitmap(160, 80, 2)
pal = displayio.Palette(2)
pal[0] = 0x000000
pal[1] = 0xffffff
tg = displayio.TileGrid(bmp, pixel_shader=pal)
splash = displayio.Group()
splash.append(tg)
fw.display.show(splash)
for x in range(40, 100):
for y in range(30, 50):
bmp[x, y] = 1
fw.display.refresh()
```
Running that with:
```
$ export BLINKA_U2IF=1
$ python3 tft_test.py
```
gets:
> Change display use to bytes

- displayio/group.py
Set the initial scale of a Group via the setter so that the associate code is run. (Closes #60)
This has been tested on Raspberry Pi 4 using `Blinka-Displayio-PyGameDisplay` to view over HDMI.
@makermelissa This may need testing on other Blinka configurations but I am happy that this change should be correct.
> Set the initial scale of a Group via the setter

- displayio/__init__.py
- displayio/i2cdisplay.py
this resolves #62 
By catching this exception we can allow much of the rest of the functionality of this library to work in environments that cannot successfully import `microcontroller`
> continue if i2cdisplay failed to import

- displayio/group.py
Add an internal _set_scale method, so that the scale can still be set from the constructor even when the scale property is over-ridden in a subclass.
Closes #64
This has been tested with the following code
```python
import terminalio
from adafruit_display_text import label
from blinka_displayio_pygamedisplay import PyGameDisplay
display = PyGameDisplay(width=320, height=240)
splash = displayio.Group(max_size=10)
display.show(splash)
lbl = label.Label(font=terminalio.FONT, text="Hello World", scale=4, x=20, y=20)
splash.append(lbl)
while display.running:
pass
```
It was also tested with the code in issue #60 and it still behaves correctly.
> Add an internal _set_scale method

- displayio/display.py
- displayio/group.py
- docs/api.rst
- docs/conf.py
Reference #67
The parameter is still allowed but will print a deprecation warning and ignore it internally.
The intention is too allow the parameter to be passed for a while until after CircuitPython 7 is released and then remove it completely. The change in this PR is not a breaking changing.
The documentation now builds entries for the classes within displayio.
> Prepare for the removal of the max_size parameter from displayio.Group

- displayio/epaperdisplay.py
As an aside, I have a three colour e-ink display on hand that I am going to try and get working with CircuitPython and Blinka on a Raspberry Pi 4.
https://shop.pimoroni.com/products/inky-phat?variant=12549254905939
It lists it as a SSD1608 in their documentation but I think that is for the two-colour variant. I'm hoping it's the SSD1680 in the three-colour.
> Update the constructor parameters of EPaperDisplay to match the core.

- .github/workflows/build.yml
- displayio/palette.py
- displayio/tilegrid.py
- docs/conf.py
- setup.py
This change makes the behavior of `Palette.__getitem__()` the same as it is in core `displayio` returning the literal int rgb888 value instead of a dictionary containing that int and a few other fields.
I tested the change successfully on Raspberry Pi 3 B+ with an ili9341 display using a "hello world" simpletest, the simpletest from Display_Shapes library, and the SwitchRound simpletest from DisplayIO_Layout library. I also verified that `make_transparent()` on the Palette object works as expected with this changes.
Also tested successfully with SwitchRound simpletest and another self-contained palette item printing example on Linux PC with my PyGameDisplay library.
> return rgba888 value from palette getitem

- displayio/_ondiskbitmap.py
Right now this property returns the image height instead of the palette or colorconverter. This changes to return the palette from the PIL Image object.
> OnDiskBitmap.pixel_shader implementation

- displayio/_display.py
I think this will resolve #77. However I have not tested the fix on hardware that needs it. I'm using a Pi 3 B+ with ili9341 display. With that environment I think it's not using data_as_command so it's not actually using this line of the driver.
Fix by moving the paren to only covert the command to bytes, then concatenate it with the data which is already type `bytes` 
Tested in python3 REPL on the Pi:
```python
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> data = b'\x00\x00\x00\xef'
>>> command = 43
>>> bytes([command]) + data
b'+\x00\x00\x00\xef'
```
> Fix for TypeError send data as command

- displayio/_display.py
Fixes #86. The problem was that Pillow's idea of rotation was the opposite direction of CircuitPython's direction.
> Make display rotation consistent with CircuitPython

- displayio/_tilegrid.py
This change adds getter and setter properties for `TileGrid.bitmap` as well as the setter property for `TileGrid.pixel_shader`
They've been implemented with the same type checking and size restrictions that are used in core displayio.
From what I can tell `pixel_shader` was already settable in the core. Bitmap accessing and setting was added with [#6270](https://github.com/adafruit/circuitpython/pull/6270)
I tested these changes successfully using essentially the same example code shown in [#6270](https://github.com/adafruit/circuitpython/pull/6270) with Blinka_DisplayIO and PyGameDisplay driver:
https://user-images.githubusercontent.com/2406189/168442359-c8f8b7b3-6088-4025-a8f2-cb3e687b9945.mp4
> bitmap getter and setter. and pixel_shader setter

- .github/workflows/build.yml
- .github/workflows/release.yml
- displayio/__init__.py
- displayio/_area.py
- displayio/_bitmap.py
- displayio/_colorconverter.py
- displayio/_colorspace.py
- displayio/_constants.py
- displayio/_display.py
- displayio/_displaybus.py
- displayio/_displaycore.py
- displayio/_epaperdisplay.py
- displayio/_fourwire.py
- displayio/_group.py
- displayio/_i2cdisplay.py
- displayio/_ondiskbitmap.py
- displayio/_palette.py
- displayio/_shape.py
- displayio/_structs.py
- displayio/_tilegrid.py
- docs/conf.py
- fontio.py
- paralleldisplay.py
- pyproject.toml
- terminalio.py
This was a good candidate for moving to `pyproject.toml` and getting the updated infrastructure as well.
Resolves #96
> Switch to pyproject.toml

- .github/workflows/build.yml
It seems actions isn't working with Python 3.11, so pinning this to an older version since Blinka is targeted at 3.7 anyways.
> Pin Python to 3.9

- displayio/_display.py
- displayio/_displaycore.py
This change  updates the APIs to match the new core API behavior. 
There is no CIRCUITPYTHON_TERMINAL for Blinka yet so that portion of the behavior is not implemented here either. 
Tested successfully on Raspberry Pi 3B+ with this tester script:
```py
import time
import board
import terminalio
from adafruit_display_text.label import Label
import adafruit_ili9341
displayio.release_displays()
spi = board.SPI()
tft_cs = board.CE0
tft_dc = board.D25
display_bus = displayio.FourWire(
spi, command=tft_dc, chip_select=tft_cs, reset=board.D24
)
display = adafruit_ili9341.ILI9341(display_bus, width=320, height=240, rotation=180)
display.brightness = 0
splash = displayio.Group()
display.show(splash)
color_bitmap = displayio.Bitmap(320, 240, 1)
color_palette = displayio.Palette(1) …
```
> root_group properties/functions on Display object and displaycore.

- displayio/_display.py
This fix prevents a thread that was stopped to be restarted.
> bugfix: prevent reuse of a stopped thread

- displayio/_tilegrid.py
The != works as an 'xor' condition on the booleans, since each of the transforms is a noop if executed twice.
This works as expected with all my existing CPy code, but I haven't done testing with a parent Group that has its own transform, so the order in which these are applied and possible interactions should still be verified against the native implementation.
Close #106
> Fix TileGrid flip_x, flip_y and transpose_xy

- .pre-commit-config.yaml
- displayio/_bitmap.py
- displayio/_tilegrid.py
- requirements.txt
- setup.py
Fixes #110. #108 fixed displayio for PIL 10.0.0, but did so using a feature that wasn't introduced until 9.2.0. This updates the requirements so that an updated version of PIL is installed.
> Updated requirements and pre-commit repo versions

- .readthedocs.yml
- docs/requirements.txt
It looks like the docs are failing because the readthedocs.yaml files hadn't been updated. This updates it and adds the correct requirements file for the docs.
> Fix failing docs

- .readthedocs.yml
It looks like #112 didn't quite work. Looking closer, it now appears to be failing because build.os was missing. I will likely need to make this change on other blinka-related repos.
> Use build.os in readthedocs.yaml

- displayio/_fourwire.py
on Odroid C4 the chip_select is controlled by the spi_meson_spicc driver, in case the SPI_CS0 is used as chip_select pin in the FourWire class Resource Busy exceptions are thrown.
> make chip_select pin optional in SPI fourwire

- displayio/_group.py
Fixes #128. I traced the issue to the root of where it was being set to a float and fixed it there.
> Fix issue where float was used when int was expected

- pyproject.toml
I noticed the new split packages were not being installed. It's because I forgot we have pyproject.toml to update now too.
> Fix pyproject.toml packages to match setup.py

- pyproject.toml
- setup.py
epaperdisplay was missing from the package list on both `setup.py` and `pyproject.toml`.
> Add missing epaperdisplay package

- displayio/__init__.py
I have not tested on hardware. 
I think this will work as a solution for https://github.com/adafruit/Adafruit_CircuitPython_SSD1322/issues/21 to allow that display driver and a few others to work under blinka displayio.
> 8.x backward compatibility

- .gitignore
- docs/conf.py
- i2cdisplaybus/__init__.py
@ladyada 
Resolves: #137. This implements the changes suggested in #138 as I understand them.
I tested this version successfully with the SSD1306 and confirmed that the sleep/wake are working as expected using the reproducer from here: https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_SSD1306/issues/47
I also tested simpletest and a few variations of it to ensure the display is initializing and drawing correctly and everything appears to behave normally to me.
Should also resolve: 
- https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_SSD1306/issues/47
- https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_SH1106/issues/21 (The only SSH1106 I have is on the macropad and I don't know if possible / how to test it with RPi.)
Also removed the `get_html_theme()` …
> I2c buffer sleepwake fix

- displayio/_bitmap.py
This now matches Circuitpython:
https://github.com/adafruit/circuitpython/blob/db4f0596abe2db49520c5e3930816ab93d66e148/shared-bindings/displayio/Bitmap.c#L46
I ran into that trying to make adafruit_imageload work with blinka .
https://github.com/adafruit/Adafruit_CircuitPython_ImageLoad/blob/c36419bcc430f33d4ec208fd290cc815d65724ab/adafruit_imageload/png.py#L127
> Accept 65536 colors bitmaps

- displayio/_group.py
@ladyada 
Resolves: #147 
Inside of `scale`, `x`, and `y` properties of Group it was using float division which ultimately raised TypeErrors when it attempted to refresh the display. 
This changes all properties to use integer division `//` 
I tested successfully with the reproducer from the issue.
> int division in group props

- displayio/_colorconverter.py
@ladyada 
Resolves: #145 
`clamp()` and the rest of convert_pixel assume that `pixel` will be a hex value, but in some cases they come in as color tuple. This converts them to hex before continuing. I tested this fix successfully with a ILI9341 on Pi4 with a modified version of the png test script from examples in the ImageLoad repo examples. I also tested ili9341_pitft_simpletest.py to ensure this change doesn't cause any issues for non-imageload usage.
> convert tuple to hex color first

- displayio/_bitmap.py
- displayio/_tilegrid.py
@ladyada 
Resolves: #150 
I believe the root cause of the issue is the refresh thread running on it's own cycle in the background while the user code is manipulating Groups, TileGrids, Bitmaps etc. which cause refresh to be needed.  I think there is a period of time during the refresh process after `_get_refresh_areas()` has been called for a given object, and before `_finish_refresh()` gets called for that same object. During that window of time if the user code manipulates the object making it need to be re-drawn it won't actually get drawn because `_finish_refresh()` gets called first which makes the next call to `_get_refresh_areas()` not return any areas to draw because `_finish_refresh()` clears / resets the dirty area to empty.
This change resolves it by adding a `_needs_refresh` …
> Refresh Fix for TileGrid

- docs/requirements.txt
@ladyada 
I think this will resolve: #151 
Updated docs requirements to match the ones in library repos e.g. https://github.com/adafruit/Adafruit_CircuitPython_CCS811/blob/main/docs/requirements.txt 
I was able to make a local docs build successfully after `pip install -r docs/requirements.txt --upgrade`  with these changes.
> update docs build reqs

- .readthedocs.yml
This is required by RTD now https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
We used adabot recently to patch many libraries with this fix, but it doesn't do the Blinka one it seems.
> declare sphinx.configuration

- displayio/__init__.py
this compatibility was removed from the core here: https://github.com/adafruit/circuitpython/pull/10193
In addition to removing the old API compatibility I changed some of the type annotations to use strings instead of imported classes in order to avoid the circular import issue, so this also resolves: #161
> remove 8.x compatibility. use strings for types to avoid circular import
